/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Music Streaming Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all mixtapes
 */
export declare const ListMixtapesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    coverUrl: zod.ZodNullable<zod.ZodString>;
    description: zod.ZodNullable<zod.ZodString>;
    releaseYear: zod.ZodNullable<zod.ZodNumber>;
    songCount: zod.ZodNumber;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
}>;
export declare const ListMixtapesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    coverUrl: zod.ZodNullable<zod.ZodString>;
    description: zod.ZodNullable<zod.ZodString>;
    releaseYear: zod.ZodNullable<zod.ZodNumber>;
    songCount: zod.ZodNumber;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
}>, "many">;
/**
 * @summary Create a new mixtape (admin only)
 */
export declare const CreateMixtapeBody: zod.ZodObject<{
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    coverUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    releaseYear: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    artist: string;
    genre: string;
    coverUrl?: string | null | undefined;
    description?: string | null | undefined;
    releaseYear?: number | null | undefined;
}, {
    title: string;
    artist: string;
    genre: string;
    coverUrl?: string | null | undefined;
    description?: string | null | undefined;
    releaseYear?: number | null | undefined;
}>;
/**
 * @summary Get a mixtape with its tracklist
 */
export declare const GetMixtapeParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetMixtapeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    coverUrl: zod.ZodNullable<zod.ZodString>;
    description: zod.ZodNullable<zod.ZodString>;
    releaseYear: zod.ZodNullable<zod.ZodNumber>;
    songCount: zod.ZodNumber;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
    songs: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        artist: zod.ZodString;
        genre: zod.ZodString;
        audioUrl: zod.ZodString;
        duration: zod.ZodNullable<zod.ZodNumber>;
        mixtapeId: zod.ZodNullable<zod.ZodNumber>;
        mixtapeTitle: zod.ZodNullable<zod.ZodString>;
        trackNumber: zod.ZodNullable<zod.ZodNumber>;
        totalPlays: zod.ZodNumber;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        trackNumber: number | null;
    }, {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        trackNumber: number | null;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
    songs: {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        trackNumber: number | null;
    }[];
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
    songs: {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        trackNumber: number | null;
    }[];
}>;
/**
 * @summary Update a mixtape (admin only)
 */
export declare const UpdateMixtapeParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateMixtapeBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    artist: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    genre: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    coverUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    releaseYear: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    title?: string | null | undefined;
    artist?: string | null | undefined;
    genre?: string | null | undefined;
    coverUrl?: string | null | undefined;
    description?: string | null | undefined;
    releaseYear?: number | null | undefined;
}, {
    title?: string | null | undefined;
    artist?: string | null | undefined;
    genre?: string | null | undefined;
    coverUrl?: string | null | undefined;
    description?: string | null | undefined;
    releaseYear?: number | null | undefined;
}>;
export declare const UpdateMixtapeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    coverUrl: zod.ZodNullable<zod.ZodString>;
    description: zod.ZodNullable<zod.ZodString>;
    releaseYear: zod.ZodNullable<zod.ZodNumber>;
    songCount: zod.ZodNumber;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    coverUrl: string | null;
    description: string | null;
    releaseYear: number | null;
    songCount: number;
    totalPlays: number;
    createdAt: Date;
}>;
/**
 * @summary Delete a mixtape (admin only)
 */
export declare const DeleteMixtapeParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List songs with optional filters
 */
export declare const ListSongsQueryParams: zod.ZodObject<{
    mixtapeId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    search: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    mixtapeId?: number | null | undefined;
    search?: string | null | undefined;
}, {
    mixtapeId?: number | null | undefined;
    search?: string | null | undefined;
}>;
export declare const ListSongsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    trackNumber: zod.ZodNullable<zod.ZodNumber>;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
}>;
export declare const ListSongsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    trackNumber: zod.ZodNullable<zod.ZodNumber>;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
}>, "many">;
/**
 * @summary Get a single song
 */
export declare const GetSongParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetSongResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
    trackNumber: zod.ZodNullable<zod.ZodNumber>;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
    comments: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        songId: zod.ZodNumber;
        name: zod.ZodString;
        text: zod.ZodString;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        songId: number;
        name: string;
        text: string;
    }, {
        id: number;
        createdAt: Date;
        songId: number;
        name: string;
        text: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
    mixtapeCoverUrl: string | null;
    comments: {
        id: number;
        createdAt: Date;
        songId: number;
        name: string;
        text: string;
    }[];
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
    mixtapeCoverUrl: string | null;
    comments: {
        id: number;
        createdAt: Date;
        songId: number;
        name: string;
        text: string;
    }[];
}>;
/**
 * @summary Update song metadata (admin only)
 */
export declare const UpdateSongParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateSongBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    genre: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    mixtapeId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    trackNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    title?: string | null | undefined;
    genre?: string | null | undefined;
    mixtapeId?: number | null | undefined;
    trackNumber?: number | null | undefined;
}, {
    title?: string | null | undefined;
    genre?: string | null | undefined;
    mixtapeId?: number | null | undefined;
    trackNumber?: number | null | undefined;
}>;
export declare const UpdateSongResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    trackNumber: zod.ZodNullable<zod.ZodNumber>;
    totalPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    trackNumber: number | null;
}>;
/**
 * @summary Delete a song (admin only)
 */
export declare const DeleteSongParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Record a play for a song
 */
export declare const RecordPlayParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const RecordPlayBody: zod.ZodObject<{
    sessionId: zod.ZodString;
    durationListened: zod.ZodNumber;
    totalDuration: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    durationListened: number;
    totalDuration: number;
}, {
    sessionId: string;
    durationListened: number;
    totalDuration: number;
}>;
export declare const RecordPlayResponse: zod.ZodObject<{
    counted: zod.ZodBoolean;
    totalPlays: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalPlays: number;
    counted: boolean;
}, {
    totalPlays: number;
    counted: boolean;
}>;
/**
 * @summary Get comments for a song
 */
export declare const GetCommentsParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetCommentsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    songId: zod.ZodNumber;
    name: zod.ZodString;
    text: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
}, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
}>;
export declare const GetCommentsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    songId: zod.ZodNumber;
    name: zod.ZodString;
    text: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
}, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
}>, "many">;
/**
 * @summary Post a comment on a song
 */
export declare const CreateCommentParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const CreateCommentBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    text: zod.ZodString;
    captchaToken: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    text: string;
    captchaToken: string;
    name?: string | undefined;
}, {
    text: string;
    captchaToken: string;
    name?: string | undefined;
}>;
/**
 * @summary Delete a comment (admin only)
 */
export declare const DeleteCommentParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Get top 10 trending songs this week
 */
export declare const GetTrendingResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
    totalPlays: zod.ZodNumber;
    weekPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}>;
export declare const GetTrendingResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
    totalPlays: zod.ZodNumber;
    weekPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}>, "many">;
/**
 * @summary Get overall analytics (admin only)
 */
export declare const GetAnalyticsOverviewResponse: zod.ZodObject<{
    totalPlaysAllTime: zod.ZodNumber;
    totalPlaysThisWeek: zod.ZodNumber;
    totalSongs: zod.ZodNumber;
    totalMixtapes: zod.ZodNumber;
    totalComments: zod.ZodNumber;
    topSongs: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        artist: zod.ZodString;
        genre: zod.ZodString;
        audioUrl: zod.ZodString;
        duration: zod.ZodNullable<zod.ZodNumber>;
        mixtapeId: zod.ZodNullable<zod.ZodNumber>;
        mixtapeTitle: zod.ZodNullable<zod.ZodString>;
        mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
        totalPlays: zod.ZodNumber;
        weekPlays: zod.ZodNumber;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }, {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }>, "many">;
    trendingThisWeek: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        artist: zod.ZodString;
        genre: zod.ZodString;
        audioUrl: zod.ZodString;
        duration: zod.ZodNullable<zod.ZodNumber>;
        mixtapeId: zod.ZodNullable<zod.ZodNumber>;
        mixtapeTitle: zod.ZodNullable<zod.ZodString>;
        mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
        totalPlays: zod.ZodNumber;
        weekPlays: zod.ZodNumber;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }, {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalPlaysAllTime: number;
    totalPlaysThisWeek: number;
    totalSongs: number;
    totalMixtapes: number;
    totalComments: number;
    topSongs: {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }[];
    trendingThisWeek: {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }[];
}, {
    totalPlaysAllTime: number;
    totalPlaysThisWeek: number;
    totalSongs: number;
    totalMixtapes: number;
    totalComments: number;
    topSongs: {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }[];
    trendingThisWeek: {
        id: number;
        title: string;
        artist: string;
        genre: string;
        totalPlays: number;
        createdAt: Date;
        audioUrl: string;
        duration: number | null;
        mixtapeId: number | null;
        mixtapeTitle: string | null;
        mixtapeCoverUrl: string | null;
        weekPlays: number;
    }[];
}>;
/**
 * @summary Get all-time top played songs
 */
export declare const GetTopSongsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
    totalPlays: zod.ZodNumber;
    weekPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}>;
export declare const GetTopSongsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    audioUrl: zod.ZodString;
    duration: zod.ZodNullable<zod.ZodNumber>;
    mixtapeId: zod.ZodNullable<zod.ZodNumber>;
    mixtapeTitle: zod.ZodNullable<zod.ZodString>;
    mixtapeCoverUrl: zod.ZodNullable<zod.ZodString>;
    totalPlays: zod.ZodNumber;
    weekPlays: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}, {
    id: number;
    title: string;
    artist: string;
    genre: string;
    totalPlays: number;
    createdAt: Date;
    audioUrl: string;
    duration: number | null;
    mixtapeId: number | null;
    mixtapeTitle: string | null;
    mixtapeCoverUrl: string | null;
    weekPlays: number;
}>, "many">;
/**
 * @summary Admin login
 */
export declare const AdminLoginBody: zod.ZodObject<{
    username: zod.ZodString;
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    password: string;
}, {
    username: string;
    password: string;
}>;
export declare const AdminLoginResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    username: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    success: boolean;
}, {
    username: string;
    success: boolean;
}>;
/**
 * @summary Admin logout
 */
export declare const AdminLogoutResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
}, {
    success: boolean;
}>;
/**
 * @summary Get current admin session
 */
export declare const GetAdminMeResponse: zod.ZodObject<{
    authenticated: zod.ZodBoolean;
    username: zod.ZodNullable<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    username: string | null;
    authenticated: boolean;
}, {
    username: string | null;
    authenticated: boolean;
}>;
/**
 * @summary List all comments for moderation (admin only)
 */
export declare const ListAllCommentsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    songId: zod.ZodNumber;
    songTitle: zod.ZodString;
    name: zod.ZodString;
    text: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
    songTitle: string;
}, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
    songTitle: string;
}>;
export declare const ListAllCommentsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    songId: zod.ZodNumber;
    songTitle: zod.ZodString;
    name: zod.ZodString;
    text: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
    songTitle: string;
}, {
    id: number;
    createdAt: Date;
    songId: number;
    name: string;
    text: string;
    songTitle: string;
}>, "many">;
/**
 * @summary Upload a new song with audio file (admin only)
 */
export declare const UploadSongBody: zod.ZodObject<{
    audio: zod.ZodType<File, zod.ZodTypeDef, File>;
    title: zod.ZodString;
    artist: zod.ZodString;
    genre: zod.ZodString;
    mixtapeId: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    trackNumber: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    artist: string;
    genre: string;
    audio: File;
    mixtapeId?: string | null | undefined;
    trackNumber?: string | null | undefined;
}, {
    title: string;
    artist: string;
    genre: string;
    audio: File;
    mixtapeId?: string | null | undefined;
    trackNumber?: string | null | undefined;
}>;
/**
 * @summary Upload a cover image for a mixtape (admin only)
 */
export declare const UploadCoverBody: zod.ZodObject<{
    cover: zod.ZodType<File, zod.ZodTypeDef, File>;
    mixtapeId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    mixtapeId: string;
    cover: File;
}, {
    mixtapeId: string;
    cover: File;
}>;
export declare const UploadCoverResponse: zod.ZodObject<{
    url: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    url: string;
}, {
    url: string;
}>;
//# sourceMappingURL=api.d.ts.map