/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Music Streaming Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all mixtapes
 */
export const ListMixtapesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  coverUrl: zod.string().nullable(),
  description: zod.string().nullable(),
  releaseYear: zod.number().nullable(),
  songCount: zod.number(),
  totalPlays: zod.number(),
  createdAt: zod.coerce.date(),
});
export const ListMixtapesResponse = zod.array(ListMixtapesResponseItem);

/**
 * @summary Create a new mixtape (admin only)
 */
export const CreateMixtapeBody = zod.object({
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  coverUrl: zod.string().nullish(),
  description: zod.string().nullish(),
  releaseYear: zod.number().nullish(),
});

/**
 * @summary Get a mixtape with its tracklist
 */
export const GetMixtapeParams = zod.object({
  id: zod.coerce.number(),
});

export const GetMixtapeResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  coverUrl: zod.string().nullable(),
  description: zod.string().nullable(),
  releaseYear: zod.number().nullable(),
  songCount: zod.number(),
  totalPlays: zod.number(),
  createdAt: zod.coerce.date(),
  songs: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      artist: zod.string(),
      genre: zod.string(),
      audioUrl: zod.string(),
      duration: zod.number().nullable(),
      mixtapeId: zod.number().nullable(),
      mixtapeTitle: zod.string().nullable(),
      trackNumber: zod.number().nullable(),
      totalPlays: zod.number(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Update a mixtape (admin only)
 */
export const UpdateMixtapeParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateMixtapeBody = zod.object({
  title: zod.string().nullish(),
  artist: zod.string().nullish(),
  genre: zod.string().nullish(),
  coverUrl: zod.string().nullish(),
  description: zod.string().nullish(),
  releaseYear: zod.number().nullish(),
});

export const UpdateMixtapeResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  coverUrl: zod.string().nullable(),
  description: zod.string().nullable(),
  releaseYear: zod.number().nullable(),
  songCount: zod.number(),
  totalPlays: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a mixtape (admin only)
 */
export const DeleteMixtapeParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List songs with optional filters
 */
export const ListSongsQueryParams = zod.object({
  mixtapeId: zod.coerce.number().nullish(),
  search: zod.coerce.string().nullish(),
});

export const ListSongsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  audioUrl: zod.string(),
  duration: zod.number().nullable(),
  mixtapeId: zod.number().nullable(),
  mixtapeTitle: zod.string().nullable(),
  trackNumber: zod.number().nullable(),
  totalPlays: zod.number(),
  createdAt: zod.coerce.date(),
});
export const ListSongsResponse = zod.array(ListSongsResponseItem);

/**
 * @summary Get a single song
 */
export const GetSongParams = zod.object({
  id: zod.coerce.number(),
});

export const GetSongResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  audioUrl: zod.string(),
  duration: zod.number().nullable(),
  mixtapeId: zod.number().nullable(),
  mixtapeTitle: zod.string().nullable(),
  mixtapeCoverUrl: zod.string().nullable(),
  trackNumber: zod.number().nullable(),
  totalPlays: zod.number(),
  createdAt: zod.coerce.date(),
  comments: zod.array(
    zod.object({
      id: zod.number(),
      songId: zod.number(),
      name: zod.string(),
      text: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Update song metadata (admin only)
 */
export const UpdateSongParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateSongBody = zod.object({
  title: zod.string().nullish(),
  genre: zod.string().nullish(),
  mixtapeId: zod.number().nullish(),
  trackNumber: zod.number().nullish(),
});

export const UpdateSongResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  audioUrl: zod.string(),
  duration: zod.number().nullable(),
  mixtapeId: zod.number().nullable(),
  mixtapeTitle: zod.string().nullable(),
  trackNumber: zod.number().nullable(),
  totalPlays: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a song (admin only)
 */
export const DeleteSongParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Record a play for a song
 */
export const RecordPlayParams = zod.object({
  id: zod.coerce.number(),
});

export const RecordPlayBody = zod.object({
  sessionId: zod.string(),
  durationListened: zod.number(),
  totalDuration: zod.number(),
});

export const RecordPlayResponse = zod.object({
  counted: zod.boolean(),
  totalPlays: zod.number(),
});

/**
 * @summary Get comments for a song
 */
export const GetCommentsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetCommentsResponseItem = zod.object({
  id: zod.number(),
  songId: zod.number(),
  name: zod.string(),
  text: zod.string(),
  createdAt: zod.coerce.date(),
});
export const GetCommentsResponse = zod.array(GetCommentsResponseItem);

/**
 * @summary Post a comment on a song
 */
export const CreateCommentParams = zod.object({
  id: zod.coerce.number(),
});

export const CreateCommentBody = zod.object({
  name: zod.string().optional(),
  text: zod.string(),
  captchaToken: zod.string(),
});

/**
 * @summary Delete a comment (admin only)
 */
export const DeleteCommentParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Get top 10 trending songs this week
 */
export const GetTrendingResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  audioUrl: zod.string(),
  duration: zod.number().nullable(),
  mixtapeId: zod.number().nullable(),
  mixtapeTitle: zod.string().nullable(),
  mixtapeCoverUrl: zod.string().nullable(),
  totalPlays: zod.number(),
  weekPlays: zod.number(),
  createdAt: zod.coerce.date(),
});
export const GetTrendingResponse = zod.array(GetTrendingResponseItem);

/**
 * @summary Get overall analytics (admin only)
 */
export const GetAnalyticsOverviewResponse = zod.object({
  totalPlaysAllTime: zod.number(),
  totalPlaysThisWeek: zod.number(),
  totalSongs: zod.number(),
  totalMixtapes: zod.number(),
  totalComments: zod.number(),
  topSongs: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      artist: zod.string(),
      genre: zod.string(),
      audioUrl: zod.string(),
      duration: zod.number().nullable(),
      mixtapeId: zod.number().nullable(),
      mixtapeTitle: zod.string().nullable(),
      mixtapeCoverUrl: zod.string().nullable(),
      totalPlays: zod.number(),
      weekPlays: zod.number(),
      createdAt: zod.coerce.date(),
    }),
  ),
  trendingThisWeek: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      artist: zod.string(),
      genre: zod.string(),
      audioUrl: zod.string(),
      duration: zod.number().nullable(),
      mixtapeId: zod.number().nullable(),
      mixtapeTitle: zod.string().nullable(),
      mixtapeCoverUrl: zod.string().nullable(),
      totalPlays: zod.number(),
      weekPlays: zod.number(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Get all-time top played songs
 */
export const GetTopSongsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  audioUrl: zod.string(),
  duration: zod.number().nullable(),
  mixtapeId: zod.number().nullable(),
  mixtapeTitle: zod.string().nullable(),
  mixtapeCoverUrl: zod.string().nullable(),
  totalPlays: zod.number(),
  weekPlays: zod.number(),
  createdAt: zod.coerce.date(),
});
export const GetTopSongsResponse = zod.array(GetTopSongsResponseItem);

/**
 * @summary Admin login
 */
export const AdminLoginBody = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export const AdminLoginResponse = zod.object({
  success: zod.boolean(),
  username: zod.string(),
});

/**
 * @summary Admin logout
 */
export const AdminLogoutResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get current admin session
 */
export const GetAdminMeResponse = zod.object({
  authenticated: zod.boolean(),
  username: zod.string().nullable(),
});

/**
 * @summary List all comments for moderation (admin only)
 */
export const ListAllCommentsResponseItem = zod.object({
  id: zod.number(),
  songId: zod.number(),
  songTitle: zod.string(),
  name: zod.string(),
  text: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListAllCommentsResponse = zod.array(ListAllCommentsResponseItem);

/**
 * @summary Upload a new song with audio file (admin only)
 */
export const UploadSongBody = zod.object({
  audio: zod.instanceof(File),
  title: zod.string(),
  artist: zod.string(),
  genre: zod.string(),
  mixtapeId: zod.string().nullish(),
  trackNumber: zod.string().nullish(),
});

/**
 * @summary Upload a cover image for a mixtape (admin only)
 */
export const UploadCoverBody = zod.object({
  cover: zod.instanceof(File),
  mixtapeId: zod.string(),
});

export const UploadCoverResponse = zod.object({
  url: zod.string(),
});
