/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Music Streaming Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
}

export interface Mixtape {
  id: number;
  title: string;
  artist: string;
  genre: string;
  /** @nullable */
  coverUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  releaseYear: number | null;
  songCount: number;
  totalPlays: number;
  createdAt: string;
}

export interface Song {
  id: number;
  title: string;
  artist: string;
  genre: string;
  audioUrl: string;
  /** @nullable */
  duration: number | null;
  /** @nullable */
  mixtapeId: number | null;
  /** @nullable */
  mixtapeTitle: string | null;
  /** @nullable */
  trackNumber: number | null;
  totalPlays: number;
  createdAt: string;
}

export interface MixtapeWithSongs {
  id: number;
  title: string;
  artist: string;
  genre: string;
  /** @nullable */
  coverUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  releaseYear: number | null;
  songCount: number;
  totalPlays: number;
  createdAt: string;
  songs: Song[];
}

export interface CreateMixtapeBody {
  title: string;
  artist: string;
  genre: string;
  /** @nullable */
  coverUrl?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  releaseYear?: number | null;
}

export interface UpdateMixtapeBody {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  artist?: string | null;
  /** @nullable */
  genre?: string | null;
  /** @nullable */
  coverUrl?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  releaseYear?: number | null;
}

export interface Comment {
  id: number;
  songId: number;
  name: string;
  text: string;
  createdAt: string;
}

export interface SongDetail {
  id: number;
  title: string;
  artist: string;
  genre: string;
  audioUrl: string;
  /** @nullable */
  duration: number | null;
  /** @nullable */
  mixtapeId: number | null;
  /** @nullable */
  mixtapeTitle: string | null;
  /** @nullable */
  mixtapeCoverUrl: string | null;
  /** @nullable */
  trackNumber: number | null;
  totalPlays: number;
  createdAt: string;
  comments: Comment[];
}

export interface UpdateSongBody {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  genre?: string | null;
  /** @nullable */
  mixtapeId?: number | null;
  /** @nullable */
  trackNumber?: number | null;
}

export interface CommentWithSong {
  id: number;
  songId: number;
  songTitle: string;
  name: string;
  text: string;
  createdAt: string;
}

export interface CreateCommentBody {
  name?: string;
  text: string;
  captchaToken: string;
}

export interface RecordPlayBody {
  sessionId: string;
  durationListened: number;
  totalDuration: number;
}

export interface PlayResult {
  counted: boolean;
  totalPlays: number;
}

export interface TrendingSong {
  id: number;
  title: string;
  artist: string;
  genre: string;
  audioUrl: string;
  /** @nullable */
  duration: number | null;
  /** @nullable */
  mixtapeId: number | null;
  /** @nullable */
  mixtapeTitle: string | null;
  /** @nullable */
  mixtapeCoverUrl: string | null;
  totalPlays: number;
  weekPlays: number;
  createdAt: string;
}

export interface AnalyticsOverview {
  totalPlaysAllTime: number;
  totalPlaysThisWeek: number;
  totalSongs: number;
  totalMixtapes: number;
  totalComments: number;
  topSongs: TrendingSong[];
  trendingThisWeek: TrendingSong[];
}

export interface AdminLoginBody {
  username: string;
  password: string;
}

export interface AdminLoginResponse {
  success: boolean;
  username: string;
}

export interface AdminSession {
  authenticated: boolean;
  /** @nullable */
  username: string | null;
}

export interface UploadSongBody {
  audio: Blob;
  title: string;
  artist: string;
  genre: string;
  /** @nullable */
  mixtapeId?: string | null;
  /** @nullable */
  trackNumber?: string | null;
}

export interface UploadCoverBody {
  cover: Blob;
  mixtapeId: string;
}

export interface UploadResult {
  url: string;
}

export type ListSongsParams = {
  /**
   * @nullable
   */
  mixtapeId?: number | null;
  /**
   * @nullable
   */
  search?: string | null;
};
